### ISSUE TITLE
BBE tests fail intermittently while verifying the output 

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-distribution#4443]
**Description:**

$title

In the output verification of the BBEs, it may fail intermittently due to the "standard-library-module pulled from central successfully" lines.

Eg:
```
ballerina/regex:1.4.3 pulled from central successfully
```
See https://scans.gradle.com/s/pmtj2vrtv5pto/console-log?task=:ballerina:testExamples#L55.

I have observed this more than one time, and it is better if we do the output verification handling those cases also, so that it does not take a longer time for the CI Ubuntu full build to pass with these intermittent failures.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
Sometimes below is also seen. See https://scans.gradle.com/s/y4ozxdtcuruyw/console-log?task=:ballerina:testExamples
```
2023-05-23T16:44:34.1838269Z Output Verification 'xml-from-record-conversion'
2023-05-23T16:44:39.1845103Z Failed due to output did not match. Line 0: ballerina/xmldata:2.4.3 pulled from central successfully
2023-05-23T16:44:39.1864287Z Failed due to output did not match. Line 2: WARNING [ballerina/xmldata/2.4.3::xmldata.bal:(58:1,58:1)] missing single backtick token
2023-05-23T16:44:39.1911314Z Failed due to output did not match. Line 3: WARNING [ballerina/xmldata/2.4.3::xmldata.bal:(392:1,400:45)] undocumented return parameter
2023-05-23T16:44:39.1911889Z Failed due to output did not match. Line 4: WARNING [ballerina/xmldata/2.4.3::xmldata.bal:(395:1,395:1)] missing double backtick token
2023-05-23T16:44:39.1913392Z Failed due to output did not match. Line 5: WARNING [ballerina/xmldata/2.4.3::xmldata.bal:(401:34,401:46)] undocumented parameter 'xmlValue'
2023-05-23T16:44:39.1914123Z Failed due to output did not match. Line 6: WARNING [ballerina/xmldata/2.4.3::xmldata.bal:(401:48,401:86)] undocumented parameter 'returnType
```

**Comment by NipunaMadhushan** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/4460

**Comment by Nadeeshan96** [comment]
Reopening the issue since the output verification of the BBEs are failed in other modules also. Please see https://github.com/ballerina-platform/ballerina-distribution/issues/4443#issue-1715117528.

**Comment by NipunaMadhushan** [comment]
This issue no longer occurs in PR checks as well as in daily builds.

**Comment by Nadeeshan96** [comment]
Reopening the issue since the problem is still observed. Please see https://github.com/ballerina-platform/ballerina-lang/actions/runs/5143063725/jobs/9259749503?pr=40473. Gradle build scan: https://scans.gradle.com/s/ppurejscwntpg/console-log?task=:ballerina:testExamples
